<?php
$todoList = $this->getData('todolist');
?>

<?php include(BASE_DIR . '/templates/head.phtml') ?>

    <h1 style="text-align:center;">To Do List</h1>

    <ul style="display:block;  border: solid black 2px; margin: 10px 20px; ">
        <?php foreach ($todoList as $todo) : ?>
            <li style="border: solid black 1px; list-style: none; margin-right: 35px; text-align: center;">
                <p>Utilisateur n° : <?= $todo['userId'] ?></p>
                <p>N° de la tâche : <?= $todo['id'] ?></p>
                <p>Nom de la tâche : <?= $todo['title'] ?></p>
                <p>Statut : <?= $todo['completed'] == 'true' ? 'Ok' : 'Ko' ?></p>
            </li>
        <?php endforeach; ?>
    </ul>

<?php include(BASE_DIR . '/templates/footer.phtml') ?>